baseURL = "https://amoustache.net/"
languageCode = "en-us"
enableEmoji = true

title = "I am A. Moustache."
copyright = "Made with ğŸ¤ ğŸš."

[build]
writeStats = true

[params]
fontawesome = "87ac18817c"
description = "Andrei MustaÈ›Äƒ (Moustache) is a software engineer, and this is his blog."
subtitle = "& this is my stuff"

[[params.links]]
url = "https://linkedin.com/in/andreimustata"
name = "Andrei MustaÈ›Äƒ on LinkedIn"
fa_logo = "linkedin"

[[params.links]]
url = "https://github.com/andreimoustache"
name = "Andrei MustaÈ›Äƒ on GitHub"
fa_logo = "github"

[[params.links]]
url = "https://stackoverflow.com/users/1148483/andrei-mustata"
name = "Andrei MustaÈ›Äƒ on StackOverflow"
fa_logo = "stack-overflow"
